name: WordPress Plugin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |-
            extends: default
            rules:
              document-start:
                present: false
              truthy:
                check-keys: false
            ignore:
              - node_modules
              - vendor

  php-lint:
    name: PHP lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: overtrue/phplint@9.7.2

  composer-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: test ! -f composer.json || composer validate --strict

  wordpress-phpunit:
    name: WordPress PHPUnit
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Run tests
        id: test
        uses: holyhope/test-wordpress-plugin-github-action@v2.0.4
        with:
          plugin_slug: cloudflare-zero-trust-login
          php_version: "8.3"

      - uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: ${{ steps.test.outputs.junit_report }}

  language-files-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: holyhope/test-wordpress-languages-github-action@v4.0.2
        id: languages
        with:
          slug: cloudflare-zero-trust-login
          exclude: |-
            .github
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: language-patch
          path: ${{ steps.languages.outputs.patch_path }}
